---

- name: install docker on ubuntu/debian using apt-get
  hosts: local
  connection: local
  become: yes
  tasks:
          - name: make sure deps are installed
            apt:
                    name: "{{ item }}"
                    update_cache: yes
                    cache_valid_time: 86400 # One day
            with_items:
                   - apt-transport-https
                   - ca-certificates
                   - curl
                   - gnupg-agent
                   - software-properties-common
          - name: install docker gpg apt key
            apt_key:
                    url: https://download.docker.com/linux/ubuntu/gpg
          - name: add docker repository
            apt_repository:
                    repo: deb https://download.docker.com/linux/ubuntu bionic stable
                    state: present
          - name: install docker through apt
            apt:
                    name: "{{ item }}"
                    update_cache: yes
                    cache_valid_time: 86400 # One day
            with_items:
                   - docker-ce
                   - docker-ce-cli
                   - containerd.io
          # https://docs.docker.com/compose/install/
          - name: get distribution
            command: uname -s
            register: distribution_name
          - name: get distribution architecture
            command: uname -m
            register: distribution_arch
          - name: download binary from docker website
            get_url:
                url: "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-{{ distribution_name.stdout }}-{{ distribution_arch.stdout }}"
                dest: /usr/local/bin/docker-compose
                mode: "+x"
          - name: add docker host line to ~/.bash_profile
            lineinfile:
                path: /home/seabass/.bash_profile
                create: yes
                state: present
                line: export DOCKER_HOST=tcp://localhost:2375
 

