---
- name: install hashicorp packer, make sure to download latest version site
  hosts: local
  gather_facts: no
  become: yes
  tasks:
    - name: download the binary from packer.io/downloads.html
      get_url:
        url: https://releases.hashicorp.com/packer/1.5.5/packer_1.5.5_linux_amd64.zip
        dest: /tmp/packer.zip
    - name: unzip file into /usr/local/bin
      unarchive:
        src: /tmp/packer.zip
        dest: /usr/local/bin
