---
- name: install hashicorp terraform version 0.12.24
  connection: local
  hosts: local
  become: yes
  tasks:
          - name: apt install deps
            apt:
                    name: unzip
                    update_cache: yes
                    cache_valid_time: 86400
          - name: download the binary from the hashicorp site
            get_url:
                    url: https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_linux_amd64.zip
                    checksum: "sha256:https://releases.hashicorp.com/terraform/0.12.24/terraform_0.12.24_SHA256SUMS"
                    dest: /tmp/
          - name: unzip binary into /usr/local/bin
            unarchive:
                    src: /tmp/terraform_0.12.24_linux_amd64.zip
                    dest: /usr/local/bin/

